In [2]:
from sklearn.model_selection import train_test_split, KFold
import numpy as np

In [5]:
# 生成從 0 到 50 的 array，並 reshape 成 (10, 5) 的 matrix
X = np.arange(50).reshape(10, 5)
 # 生成一個全零 arrary
y = np.zeros(10)
# 將一半的值改為 1
y[:5] = 1
print("Shape of x :", X.shape)
print("Shape of y :", y.shape)


Shape of x : (10, 5)
Shape of y : (10,)


In [7]:
print('X : shape  ' + str(X.shape))
print(X)
print("")
print('y : shape ' + str(y.shape))
print('y : shape : ' + str(y.shape))
print(y)

X : shape  (10, 5)
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]]

y : shape (10,)
y : shape : (10,)
[1. 1. 1. 1. 1. 0. 0. 0. 0. 0.]


In [10]:
X_train, X_test, y_train, y_trst = train_test_split(X, y, test_size = 2, random_state = 0)

In [15]:
X_train

array([[20, 21, 22, 23, 24],
       [45, 46, 47, 48, 49],
       [ 5,  6,  7,  8,  9],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [15, 16, 17, 18, 19],
       [ 0,  1,  2,  3,  4],
       [25, 26, 27, 28, 29]])

In [16]:
y_train

array([1., 0., 1., 0., 0., 1., 1., 0.])

In [21]:
kf = KFold(n_splits = 5)
i = 0
for train_index, test_index in kf.split(X) :
    i +=1
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]
    print("FOLD {} : ".format(i))
    print("X_test :", X_test)
    print("Y_test :", y_test)
    print("-"*30)

FOLD 1 : 
X_test : [[0 1 2 3 4]
 [5 6 7 8 9]]
Y_test : [1. 1.]
------------------------------
FOLD 2 : 
X_test : [[10 11 12 13 14]
 [15 16 17 18 19]]
Y_test : [1. 1.]
------------------------------
FOLD 3 : 
X_test : [[20 21 22 23 24]
 [25 26 27 28 29]]
Y_test : [1. 0.]
------------------------------
FOLD 4 : 
X_test : [[30 31 32 33 34]
 [35 36 37 38 39]]
Y_test : [0. 0.]
------------------------------
FOLD 5 : 
X_test : [[40 41 42 43 44]
 [45 46 47 48 49]]
Y_test : [0. 0.]
------------------------------


In [42]:
#作業
x= np.arange(1000).reshape(200, 5)
y = np.zeros(200)
y[:40] =1
print("Shape of x: ", x.shape)
print("Shape of y: ", y.shape)

Shape of x:  (200, 5)
Shape of y:  (200,)


In [43]:
y

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [45]:
y0 = y[y == 0]
y1 = y[y == 1]

In [48]:
y_train0, y_test0 = train_test_split(y0, test_size = 0.33, random_state = 42)
y_train1, y_test1 = train_test_split(y1, test_size = 0.25, random_state = 42)

In [35]:
print('x: shape: ' + str(x.shape))
print(x)
print("")
print('y: shape: ' + str(y.shape))
print(y)

x: shape: (200, 5)
[[  0   1   2   3   4]
 [  5   6   7   8   9]
 [ 10  11  12  13  14]
 [ 15  16  17  18  19]
 [ 20  21  22  23  24]
 [ 25  26  27  28  29]
 [ 30  31  32  33  34]
 [ 35  36  37  38  39]
 [ 40  41  42  43  44]
 [ 45  46  47  48  49]
 [ 50  51  52  53  54]
 [ 55  56  57  58  59]
 [ 60  61  62  63  64]
 [ 65  66  67  68  69]
 [ 70  71  72  73  74]
 [ 75  76  77  78  79]
 [ 80  81  82  83  84]
 [ 85  86  87  88  89]
 [ 90  91  92  93  94]
 [ 95  96  97  98  99]
 [100 101 102 103 104]
 [105 106 107 108 109]
 [110 111 112 113 114]
 [115 116 117 118 119]
 [120 121 122 123 124]
 [125 126 127 128 129]
 [130 131 132 133 134]
 [135 136 137 138 139]
 [140 141 142 143 144]
 [145 146 147 148 149]
 [150 151 152 153 154]
 [155 156 157 158 159]
 [160 161 162 163 164]
 [165 166 167 168 169]
 [170 171 172 173 174]
 [175 176 177 178 179]
 [180 181 182 183 184]
 [185 186 187 188 189]
 [190 191 192 193 194]
 [195 196 197 198 199]
 [200 201 202 203 204]
 [205 206 207 208 209]
 [210 211 212 2

In [49]:
y_train = np.append(y_train0, y_train1)
y_test = np.append(y_test0, y_test1)

In [36]:
####
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.3, random_state =52)

In [38]:
x_train

array([[740, 741, 742, 743, 744],
       [ 30,  31,  32,  33,  34],
       [350, 351, 352, 353, 354],
       [285, 286, 287, 288, 289],
       [905, 906, 907, 908, 909],
       [625, 626, 627, 628, 629],
       [915, 916, 917, 918, 919],
       [830, 831, 832, 833, 834],
       [440, 441, 442, 443, 444],
       [375, 376, 377, 378, 379],
       [225, 226, 227, 228, 229],
       [305, 306, 307, 308, 309],
       [230, 231, 232, 233, 234],
       [290, 291, 292, 293, 294],
       [365, 366, 367, 368, 369],
       [220, 221, 222, 223, 224],
       [750, 751, 752, 753, 754],
       [565, 566, 567, 568, 569],
       [435, 436, 437, 438, 439],
       [500, 501, 502, 503, 504],
       [980, 981, 982, 983, 984],
       [415, 416, 417, 418, 419],
       [405, 406, 407, 408, 409],
       [785, 786, 787, 788, 789],
       [255, 256, 257, 258, 259],
       [ 95,  96,  97,  98,  99],
       [805, 806, 807, 808, 809],
       [160, 161, 162, 163, 164],
       [560, 561, 562, 563, 564],
       [845, 8

In [39]:
y_train

array([0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 1., 1.,
       0., 1., 0., 0., 1., 1., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0.,
       0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
       0., 1., 0., 0., 1., 1., 0., 0., 0., 1., 1., 0., 0., 1., 1., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0.,
       1., 1., 0., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 0., 0., 0., 0.,
       0., 1., 1., 0.])

In [41]:
kf = KFold(n_splits = 5)
i = 0
for train_index, test_index in kf.split(x):
    i += 1
    x_train, x_test = x[train_index], x[test_index]
    y_train, y_test = y[train_index], y[test_index]
    print("FOLD {} : ".format(i))
    print("X_test : ", x_test)
    print("Y_test : ", y_test)
    print("="*40)

FOLD 1 : 
X_test :  [[  0   1   2   3   4]
 [  5   6   7   8   9]
 [ 10  11  12  13  14]
 [ 15  16  17  18  19]
 [ 20  21  22  23  24]
 [ 25  26  27  28  29]
 [ 30  31  32  33  34]
 [ 35  36  37  38  39]
 [ 40  41  42  43  44]
 [ 45  46  47  48  49]
 [ 50  51  52  53  54]
 [ 55  56  57  58  59]
 [ 60  61  62  63  64]
 [ 65  66  67  68  69]
 [ 70  71  72  73  74]
 [ 75  76  77  78  79]
 [ 80  81  82  83  84]
 [ 85  86  87  88  89]
 [ 90  91  92  93  94]
 [ 95  96  97  98  99]
 [100 101 102 103 104]
 [105 106 107 108 109]
 [110 111 112 113 114]
 [115 116 117 118 119]
 [120 121 122 123 124]
 [125 126 127 128 129]
 [130 131 132 133 134]
 [135 136 137 138 139]
 [140 141 142 143 144]
 [145 146 147 148 149]
 [150 151 152 153 154]
 [155 156 157 158 159]
 [160 161 162 163 164]
 [165 166 167 168 169]
 [170 171 172 173 174]
 [175 176 177 178 179]
 [180 181 182 183 184]
 [185 186 187 188 189]
 [190 191 192 193 194]
 [195 196 197 198 199]]
Y_test :  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 